name = "Forever Pack"
author = "KaduCmK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "960be84c04bbb2fb19934d2fc0bc74ab46914572cf3364ce1d9ca03862bc2f87"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
