name = "Forever Pack"
author = "KaduCmK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2dc05817c6592a2c509991435e4362bb89f2d97941ef35248ee67f7e833b3ff"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
