name = "Forever Pack"
author = "KaduCmK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44fabb3b99389e3f0b3d6817d8c39a6bade2843540a6831c89b9ca0d6203b487"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
